Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,4 +12,8 @@ jobs:
           java-version: 21
       - run: |
           echo "Attempting to download leiningen"
-          sudo apt install leiningen && echo "Successfully installed leiningen" || echo "Error installing leiningen"
+          sudo apt install leiningen && echo "Successfully installed leiningen" || echo "Failed to install leiningen"
+          echo "Testing clojure and lein"
+          echo '(println "A string in clojure")' | lein repl 
+          
+          
